[package]
name = "sile"
version = "0.14.8"
edition = "2021"
description = "Simon’s Improved Layout Engine"
authors = [
  "Simon Cozens",
  "Caleb Maclennan <caleb@alerque.com>",
  "Olivier Nicole",
  "Didier Willis"
]
rust-version = "1.68"
homepage = "https://sile-typesetter.org"
license = "MIT"
build = "build.rs"

[[bin]]
name = "sile"
required-features = ["cli"]

[dependencies]

  [dependencies.clap]
  version = "4.2"
  optional = true
  features = [ "derive", "wrap_help" ]

  [dependencies.mlua]
  version = "0.8"
  features = [ "lua54", "vendored" ]

[build-dependencies]

  [build-dependencies.clap_complete]
  version = "4.2"
  optional = true

  [build-dependencies.clap_mangen]
  version = "0.2"
  optional = true

  [build-dependencies.clap]
  version = "4.0"
  optional = true
  features = [ "derive" ]

  [build-dependencies.vergen]
  version = "7.4"
  default-features = false
  features = [ "build", "git" ]

[features]
default = ["cli", "bash", "elvish", "fish", "manpage", "powershell", "zsh"]
completions = ["cli", "clap_complete"]
cli = ["clap"]
bash = ["completions"]
elvish = ["completions"]
fish = ["completions"]
manpage = ["clap_mangen"]
powershell = ["completions"]
zsh = ["completions"]

[profile.release]
lto = true
