name: Test

on: [push, pull_request]

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.4", "5.3", "5.2", "5.1", "luajit", "luajit-openresty"]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache test fonts
        uses: actions/cache@v2
        with:
          path: |
            .fonts
            .sources
          key: fonts-${{ hashFiles('Makefile-fonts') }}
      - name: Cache lua_modules
        uses: actions/cache@v2
        with:
          path: |
            lua_modules
          key: luarocks-${{ hashFiles('Makefile-luarocks', 'sile-dev-1.rockspec') }}
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@v4
      - name: Prep system Lua for use
        run: |
          luarocks install busted
          function deepest () { find $1 -type d | awk 'length>m{m=length;r=$0}END{print r}'; }
          cat << EOF >> $GITHUB_ENV
          LD_LIBRARY_PATH=$PWD/.lua/lib:$LD_LIBRARY_PATH
          LIBRARY_PATH=$PWD/.lua/lib:$LIBRARY_PATH
          LD_RUN_PATH=$PWD/.lua/lib:$LD_RUN_PATH
          PKG_CONFIG_PATH=$PWD/.lua/lib/pkgconfig:$PKG_CONFIG_PATH
          LUA_INCLUDE=-I$(deepest $PWD/.lua/include)
          MAKEFLAGS=-j$(nproc) -Otarget
          EOF
      - name: Install system dependencies
        run: |
          sudo apt-get install libarchive-tools libfontconfig1-dev libharfbuzz-dev libicu-dev libpng-dev poppler-utils
      - name: Configure
        run: |
          ./bootstrap.sh
          ./configure --without-system-luarocks --with${{ startsWith(matrix.luaVersion, '5') && 'out' || '' }}-luajit --without-manual --without-examples
      - name: Make
        run: |
          make
      - name: Test Busted
        run: |
          make busted
      - name: Test Regressions
        run: |
          make regressions
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-actuals
          path: tests/*.actual
